[package]
name = "portside-tui"
version = "0.1.0"
edition = "2024"
description = "A terminal UI for tracking work sessions"
license = "Unlicense OR MIT"
authors = ["JayanAXHF <sunil.chdry@gmail.com>"]
homepage = "https://github.com/jayanaxhf/portside"
repository = "https://github.com/jayanaxhf/portside"
readme = "README.md"
keywords = ["tui", "cli", "github", "productivity", "ratatui"]
categories = ["command-line-utilities", "command-line-interface"]

[dependencies]
crossterm = "0.29.0"
directories = "6.0.0"
ratatui = "0.30.2"
ratatui-toaster = "0.1.4"
notify-rust = "4"
rusqlite = { version = "0.40.1", features = ["bundled"] }
thiserror = "2.0.19"
time = { version = "0.3.55", features = ["formatting", "parsing", "local-offset", "macros"] }
tui-big-text = "0.8.8"

[[bin]]
name = "portside"
path = "src/bin/portside.rs"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/{ name }-v{ version }/{ name }-{ target }-v{ version }{ archive-suffix }"
